"use client";

import { useState } from "react";
import { saveConsolidatedSummary } from "@/lib/actions";

// The Blueprint is no longer generated by a single click here — it generates
// automatically once every assigned clinician signs off the consolidated
// summary (in their workspace's Summaries tab). This control just lets an
// admin/clinician author or edit that consolidated summary.
export default function BlueprintGenerate({
  clientId, generated, consolidated,
}: { clientId: string; generated: boolean; ready?: boolean; consolidated: string | null }) {
  const [open, setOpen] = useState(false);

  if (generated) {
    return <span style={{ background: "var(--green-bg)", color: "var(--green-text)", borderRadius: 999, padding: "3px 10px", fontSize: 12, fontWeight: 600 }}>Generated</span>;
  }

  return (
    <div>
      <button type="button" onClick={() => setOpen((o) => !o)} style={{ border: "1px solid var(--border)", background: "#fff", color: "var(--ink)", borderRadius: 8, padding: "6px 11px", fontSize: 12, cursor: "pointer" }}>
        {open ? "Cancel" : "Consolidated summary"}
      </button>
      {open && (
        <form action={saveConsolidatedSummary} style={{ marginTop: 8 }}>
          <input type="hidden" name="client_id" value={clientId} />
          <textarea
            name="consolidated" rows={3} defaultValue={consolidated ?? ""}
            placeholder="Consolidated summary across all consultations…"
            style={{ width: 320, maxWidth: "100%", padding: "8px 10px", border: "1px solid var(--border)", borderRadius: 8, fontSize: 13, background: "#fff" }}
          />
          <div style={{ marginTop: 6 }}>
            <button type="submit" style={{ background: "var(--ink)", color: "#fff", border: "none", borderRadius: 8, padding: "7px 13px", fontSize: 12, fontWeight: 600, cursor: "pointer" }}>
              Save
            </button>
            <div style={{ fontSize: 11, color: "var(--muted)", marginTop: 6, maxWidth: 320 }}>
              Generates automatically once all assigned clinicians sign off (Summaries tab).
            </div>
          </div>
        </form>
      )}
    </div>
  );
}
